### ISSUE TITLE
Error in event for onInstaled

### ISSUE THREAD

**Issue by michelmelo** [Pushwoosh/web-push-notifications#1]
when I run the example of error in instaled
![captura de tela 2014-09-19 10 30 33](https://cloud.githubusercontent.com/assets/159223/4333382/a75269a6-3fdf-11e4-8879-0f339e47c562.png)

**Comment by FallDi** [comment]
Hello!
We have fixed this problem. Please re-download extension and try again. Also you can download it from https://chrome.google.com/webstore/detail/pushwoosh-gcm-notificatio/ndeeiaalfemhaahglpildclkgilgnfce?authuser=1

**Comment by michelmelo** [comment]
tks
