### ISSUE TITLE
Issues with 3.0

### ISSUE THREAD

**Issue by asvetliakov** [Pushwoosh/web-push-notifications#12]
Hello,
I'm getting following unresolved constants:
ReferenceError: ```__API_URL__``` is not defined
ReferenceError:``` __DEV_MODE__``` is not defined

Perhaps you need to use webpack DefinePlugin or so 😃 
I was able to pass ```__DEV_MODE__``` constant but i don't know what's api url should be

Also, since the lib was rewritten to typescript, can you generate & include typescript definition files into npm module?

**Comment by bisserof** [comment]
Hello, @asvetliakov 

1) As i suppose, you use npm package. So you can install just published version with fixes of these strange bugs.
2) npm module is already transpiled to plain javascript.

**Comment by asvetliakov** [comment]
@bisserof 
2. I mean to include typescript "*.d.ts" files into npm module along with transpiled javascript (Flag ```-d with tsc```) so the lib can be consumed by typescript without manually writing definition files or using allowJs.
Thanks.
