### ISSUE TITLE
Include typescript definitions in npm package

### ISSUE THREAD

**Issue by fikus** [Pushwoosh/web-push-notifications#15]
Please include the typescript definitions in the npm package so users of the library can take advantage of them.

**Comment by wfhm** [comment]
Hi,

Thank you for a suggestion! It will be added in the upcoming releases.

**Comment by wfhm** [comment]
@fikus 

We've added typisation to the project, [npm package](https://www.npmjs.com/package/web-push-notifications) is updated.
