### ISSUE TITLE
PushWoosh SDK since 3.1.0 not working

### ISSUE THREAD

**Issue by lgordey** [Pushwoosh/web-push-notifications#16]
Hi!

I have pushwoosh SDK **3.0.8** installed with your package on several sites and it works fine.
But when I try to update on **3.1.0** or later - it stop working as well (service worker didn't install or update, pushwoosh didnt init).
And after I rollback to **3.0.8** - it's fine again.

I guess you changed smth important in this commit https://github.com/Pushwoosh/web-push-notifications/commit/84804e0b6afe9d2ec022bed2fec4213d8ff07d7a

So maybe you have new requirements about some environment things or etc?

Thanks in advance for the help!

**Comment by roman-solomaha** [comment]
@lgordey can you give us your init params configuration?

**Comment by lgordey** [comment]
I have the same fields as
```javascript
pushWoosh.push(['init', {
  logLevel: 'error',
  applicationCode: 'XXXXX-XXXXX',
  safariWebsitePushID: 'web.com.example.domain',
  defaultNotificationTitle: 'Pushwoosh',
  defaultNotificationImage: '/logo-medium.png',
}]);
```
Now I see a couple of errors:

![image](https://user-images.githubusercontent.com/5946242/35146538-6608bcae-fd1c-11e7-9ed9-dfa8193c918b.png)
![image](https://user-images.githubusercontent.com/5946242/35146577-867c4550-fd1c-11e7-8bb6-504ecea3d6e4.png)

But the same project/code works at localhost correct (with 3.1.2) - not in production.
And version 3.0.8 works well on both - localhost and production as well.

Magic?) 🤔

**Comment by roman-solomaha** [comment]
@lgordey Yeah, it sure does look like magic.
Could you describe how you handle the SDK integration?
If you use the npm, please show the code where the SDK is imported into a variable and the code with init params.

Also, please tell me which builder you’re using, and where our SDK is when the build’s ready. Perhaps you’re using any third party plugins for minification?

It looks very much like Pushwoosh object’s context gets lost while initializing the SDK. Try to test a production build without any minification and obfuscation.

**Comment by lgordey** [comment]
I think you are right.
I'm using `webpack` v1, it has default `devtool` for development and production.
https://webpack.js.org/configuration/devtool/

It work correct only with `eval` - all other options (like for prod) prevent pushwoosh from working 😕

**Comment by lgordey** [comment]
Ok, so in fact `UglifyJsPlugin` is the main one here.
But I have it with default configuration - just no options and run build with `-p` flag.

**Comment by lgordey** [comment]
Mm, so I need to split pushwoosh to separate chunk and exclude from uglifyJS.
Cause from version 3.1.0 something goes wrong with `web-push-notifications` minification and obfuscation.
But I guess I will just load it from `cdn` 😃 

Thanks for help
