### ISSUE TITLE
TypeError: ServiceWorker script at http://localhost:8100/pushwoosh-service-worker.js?version=3.1.4 for scope http://localhost:8100/ encountered an error during installation.

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/web-push-notifications#17]
I see error 
When i use ionic 3 
and your package 

TypeError: ServiceWorker script at http://localhost:8100/pushwoosh-service-worker.js?version=3.1.4 for scope http://localhost:8100/ encountered an error during installation.

Here is my ionic info

cli packages: 

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.3
    npm               : 5.5.1
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Program Files (x86)\Android\android-sdk

Misc:

    backend : pro

And yes i have used service worker and included 
importScripts('https://cdn.pushwoosh.com/webpush/v3/pushwoosh-service-worker.js');

**Comment by roman-solomaha** [comment]
Hello @ipehimanshu 
Can you give us your init params configuration and how you import web-push-notifications into your application?

**Comment by wfhm** [comment]
@ipehimanshu Could you please provide us with any update on this issue? Is it still persistent or were you able to solve it on your own?
