### ISSUE TITLE
TypeScript cause type error

### ISSUE THREAD

**Issue by MrZaYaC** [Pushwoosh/web-push-notifications#18]
`ERROR in node_modules/web-push-notifications/lib/index.d.ts(67,26): error TS2304: Cannot find name 'IPWParams'.`

It is because you declare `interface PWParams` instead `IPWParams`

**Comment by phobos1** [comment]
Thank you for your request. We will fix it asap.

**Comment by MrZaYaC** [comment]
fixed in 3.2.5
Thank you!
