### ISSUE TITLE
module ios

### ISSUE THREAD

**Issue by michelmelo** [Pushwoosh/web-push-notifications#2]
which the possibilities of a module of the same iOS (titanium)?

**Comment by shaders** [comment]
Sorry, I do not understand the question.

**Comment by michelmelo** [comment]
I use titanium, and the iOS pushwoosh not even have a module. You are using functions to get the push, which would be to have the rich pages, but the magnitude of titanium for iOS does not have it.

**Comment by shaders** [comment]
Pushwoosh for Titanium now does have iOS modue
