### ISSUE TITLE
Web push notifications not working in chrome browser

### ISSUE THREAD

**Issue by guptashivanshu** [Pushwoosh/web-push-notifications#21]
Hi,
I integrated Pushwoosh web push notifications to my PWA, After integration, I tested it with Firefox and Google Chrome Browser (Both mobile and desktop) by sending push notifications from Pushwoosh dashboard.
I am getting push notifications on Firefox (mobile and desktop) and i am impressed with your service for Firefox browser but i am not getting any notification in Google Chrome Browser (Both mobile and desktop).

FCM and sender id is already configured before doing this.

**Some Information about how i am accessing:**
1. First of all i am running latest version of google chrome and using it's default window (not in incognito or guest mode) and , No Adblocker is enabled.
2. I am using Pushwoosh notification in debug mode.
3. Then i visit my website which is running on HTTPS and have Let's Encrypt SSL installed on the server. 
4. Then notification permission window pops up and i click on allow button. Then some info were added in chrome console
5. I scanned the console and no error was there from Pushwoosh (only info is displayed).
6. After this i am pushing notifications by targeting Google Chrome and Firefox Browser in Pushwoosh dashboard.

I am getting notifications in Firefox but not in Google Chrome Browser. I also tried it on another website which is using cPanel Auto SSL from Comodo and same results are there.

Any idea what i am missing?? Can you please guide me how to resolve that issue. If you need any information, please let me know.

Thanks

**Comment by wfhm** [comment]
Hello @guptashivanshu ,

1. It is worth checking whether everything is OK when receiving pushes on your Chrome. We recommend doing it with our Web SDK sample. Just go to your Control Panel, choose Pushwoosh Demo App and click on Chrome icon in "Get PushOn app..." tab - it will automatically redirect you to a website which is subscribed for this particular application:
![screenshot 2018-10-29 at 15 23 17](https://user-images.githubusercontent.com/13344781/47641628-1eeb0c80-db99-11e8-928e-356a77a57f4d.png)


Please try subscribing for pushes using this website. If your browser receives pushes just fine, please share your Pushwoosh integration code (on any of your test builds).

**Comment by wfhm** [comment]
@guptashivanshu any news? Have you been able to solve the issue or do you require any additional assistance?
