### ISSUE TITLE
Can you help to add for ionic 4 or ionic 5

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/web-push-notifications#24]
Hello sir

can you help us to add for ionic 4 or ionic 5?

**Comment by wfhm** [comment]
@ipehimanshu this is the repository of our Web SDK, which is used in web apps, not in mobile or desktop ones.

For what platform do you want to build an Ionic app - is that mobile or desktop? Do you have a React-, Angular-, or Vue-based Ionic project? What exactly is the issue that you struggle with?
