### ISSUE TITLE
Error: Internal error: Can't register device in fcm. Status: 503

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/web-push-notifications#25]
Hello 
Can you please help us to solve this issue.
![image](https://user-images.githubusercontent.com/26652038/124593350-2ac81a00-de7c-11eb-9a35-e49af9143898.png)

Thanks

**Comment by wfhm** [comment]
@ipehimanshu This is a Web SDK repository, but I can see that Cordova is mentioned in the logs. Could you please clarify what framework you use, and when exactly you get this error?

**Comment by ipehimanshu** [comment]
created support ticket
