### ISSUE TITLE
not working on chrome

### ISSUE THREAD

**Issue by jaryroxas** [Pushwoosh/web-push-notifications#3]
hi, 
followed every bit of instruction 
https://www.pushwoosh.com/programming-push-notification/chrome/chrome-web-push/

im also in https but not sure why it is not workig, is there a special setup to make this work?

**Comment by FallDi** [comment]
Hello!

Can you provide link of you web site with manifest and .js files?

**Comment by timhtheos** [comment]
+1

**Comment by timhtheos** [comment]
@FallDi https://www.timothyae.com

I believe I have the same issue with @jaryroxas.

**Comment by FallDi** [comment]
In you console.log I see such error message "Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script." 
![screenshot1](http://screenshu.com/static/uploads/temporary/b4/6o/49/e3vpm6.jpg)
Chrome pushes not working with self-signed certificates(https/ssl). You should get SSL certificate signed by trusted center for example http://www.verisign.com/.

Or you can run chrome from command line with option -ignore-certificate-errors(like chrome.exe -ignore-certificate-errors) and then you will can to subscribe for push notifications 
![screenshot1](http://screenshu.com/static/uploads/temporary/hr/im/k4/ynzggb.jpg)

**Comment by timhtheos** [comment]
@FallDi thanks. I got it working now. :)

**Comment by FallDi** [comment]
You are welcome ;)
