### ISSUE TITLE
add pushwoosh to NextJS 10 but not getting notification when test (local host 3000)

### ISSUE THREAD

**Issue by pxman1012** [Pushwoosh/web-push-notifications#31]
Hi all, I am integrating pushwoosh into nextjs version 10, but when testing locally, I do not receive notifications

![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/9c49a800-4eee-4a8b-93d7-3d6037eee7ed)
![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/52ce73d7-744a-4be2-aedf-8389d4d87242)
![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/04a489dd-cced-4e84-aea3-1041b12cd670)

**Comment by enginseer-dev** [comment]
Hello, @pxman1012 

The Pushwoosh SDK may not be functioning properly if it is implemented to a website hosted locally.
Can you please try to host the website for example on Firebase and update us on the result?
In this case we will also be able to troubleshoot the integration from our side.

**Comment by pxman1012** [comment]
Hi @enginseer-dev 

I am using firebase 

![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/fa9362ab-0d00-49e0-af2d-4af343283f1e)

**Comment by pxman1012** [comment]
I test pushwoosh only get info in console from pushwoosh-service-worker.js (chrome) but not show notice popup like example

![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/78eea763-4420-4294-b9f7-2322ecc7a573)
![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/2580bf6d-b02f-416a-adce-849483b70f80)

**Comment by enginseer-dev** [comment]
@pxman1012 I see on your screenshot that no devices have subscribed to the notifications.
Can you please double-check if you've enabled subscription prompt?
Here is the related manual: https://docs.pushwoosh.com/platform-docs/send-messages/push-notifications/subscription-prompt/default-widget#creating-a-default-widget

**Comment by pxman1012** [comment]
@enginseer-dev I have turned on both manual and automatic notifications, but I still don't receive a notification popup

![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/09b85147-ad80-4db1-8322-2d1a2a45cf79)
![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/bbbf9661-96f0-4d45-8781-dc7e29a19acc)

**Comment by enginseer-dev** [comment]
@pxman1012, thank you for sharing your screenshot. It appears that your website is currently hosted locally. This setup might prevent the Pushwoosh SDK from operating as expected. For optimal functionality, we recommend hosting your website on a platform like Firebase.

If your website is already live on a server, could you please share the URL with us? This will allow us to investigate the issue. For privacy and security, kindly submit the website link through a support ticket at help@pushwoosh.com.

**Comment by pxman1012** [comment]
@enginseer-dev this is my website https://nextjs-pushwoosh.vercel.app/

**Comment by enginseer-dev** [comment]
@pxman1012 I've tested your integration by subscribing to notifications and I've successfully received the push notification:

![image](https://github.com/Pushwoosh/web-push-notifications/assets/139750027/4852639a-093e-46c5-a3a1-50317c14ab46)

Please clean your browser's temporary files and remove the push notification settings for the website. 
For Google Chrome, you can do this by navigating to:
[chrome://settings/content/notifications](chrome://settings/content/notifications)

**Comment by pxman1012** [comment]
@enginseer-dev I did but it only shows the information in the browser console and not the popup

![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/af98efe4-cb8e-4548-a38c-78ba198cf040)
![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/c08157ab-6ede-4139-8309-b8793de75ff8)

**Comment by enginseer-dev** [comment]
@pxman1012 I've successfully received the test notifications you sent, indicating that the integration is functioning correctly:

![image](https://github.com/Pushwoosh/web-push-notifications/assets/139750027/715b29d0-b036-4160-992f-7998e8a86e10)
![image](https://github.com/Pushwoosh/web-push-notifications/assets/139750027/747f9792-4f08-4581-a7b4-dc528a4e3623)

It appears the difficulty you're encountering might be specific to your browser. 
I recommend conducting a test on a different device or with an alternate Google account to see if the issue persists.

Occasionally, certain browser configurations or Chrome extensions can interfere with the delivery of notifications. 
Adjusting these settings or temporarily disabling extensions may help identify the cause.

**Comment by pxman1012** [comment]
@enginseer-dev  I have reconfigured the settings under windows and it has popped up
Thank u very much

![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/30c6c54b-8121-47dc-b1ec-0c3d30dbb772)

![image](https://github.com/Pushwoosh/web-push-notifications/assets/70894756/5f95fde2-effc-46cf-84cc-0c9e6badb01e)

**Comment by enginseer-dev** [comment]
@pxman1012 We're glad to help!

Feel free to message us, if you have any questions.
