### ISSUE TITLE
Manually trigger subscribePopup

### ISSUE THREAD

**Issue by finnan444** [Pushwoosh/web-push-notifications#32]
Is it possible to trigger **subscribePopup** on custom event instead of setting `delay` property?
When my custom event is triggered i call `Pushwoosh.subscribePopup.toggle(true)` but i am not sure if **subscribePopup** will be shown twice when delay will fire.
BTW, where is the repo with source code of @pushwoosh/web-push-subscribe-popup? And also it is now of version [1.0.14](https://www.npmjs.com/package/@pushwoosh/web-push-subscribe-popup/v/1.0.14) but in dependencies i see `"@pushwoosh/web-push-subscribe-popup": "1.0.7"`

**Comment by enginseer-dev** [comment]
Hello, @finnan444 

> Is it possible to trigger subscribePopup on custom event instead of setting delay property?
> When my custom event is triggered i call Pushwoosh.subscribePopup.toggle(true) but i am not sure if subscribePopup will be shown twice when delay will fire.

Here is an example on how to call pop-up on a custom event:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pushwoosh Web SDK Sample</title>
    <link rel="manifest" href="/manifest.json">
    <script src="https://cdn.pushwoosh.com/webpush/v3/pushwoosh-web-notifications.js" async></script>
    <script>
        var Pushwoosh = Pushwoosh || [];
        Pushwoosh.push(["init", {
            logLevel: 'error',
            applicationCode: 'APP_CODE',
            safariWebsitePushID: 'web.com.example.domain',
            defaultNotificationTitle: 'Pushwoosh',
            defaultNotificationImage: 'https://cp.pushwoosh.com/img/logo-medium.png',
            autoSubscribe: false, // Handle subscription manually
            userId: 'user_id',
            tags: {
                'Name': 'John Smith'
            }
        }]);
    </script>
</head>
<body>
    <h1>Pushwoosh Web SDK usage sample!</h1>
    <button id="subscribeButton">Subscribe to Notifications</button>
    
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var subscribeButton = document.getElementById('subscribeButton');
            subscribeButton.addEventListener('click', function() {
                Pushwoosh.subscribe();
            });
        });
    </script>
</body>
</html>
```

Here you can find the live example:
https://pushwoosh-f2364.firebaseapp.com/ 

> BTW, where is the repo with source code of @pushwoosh/web-push-subscribe-popup? And also it is now of version [1.0.14](https://www.npmjs.com/package/@pushwoosh/web-push-subscribe-popup/v/1.0.14) but in dependencies i see "@pushwoosh/web-push-subscribe-popup": "1.0.7"

Currently you can view the code by following this link:
https://www.npmjs.com/package/@pushwoosh/web-push-subscribe-popup/v/1.0.14?activeTab=code 

I'll check internally with the team and will get back to you regarding the 1.0.7 version in the dependencies.

**Comment by finnan444** [comment]
@enginseer-dev the example you provided works, but it shows browser default popup - but i am talking about [custom-subscription-popup](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/web-push-notifications/custom-subscription-popup#implementation). 

In the live example by the way the subscription-popup is shown - but i believe because you enabled it like described [here](https://docs.pushwoosh.com/platform-docs/send-messages/push-notifications/subscription-prompt/default-widget)
![Screenshot 2024-05-16 at 15 52 21](https://github.com/Pushwoosh/web-push-notifications/assets/28092100/6f008c8b-04c1-407b-a373-135127886b2a)

**Comment by enginseer-dev** [comment]
@finnan444, we have tested internally and, unfortunately, it's not possible to set a custom subscription popup to work with a custom event at this time.

However, we are planning to update our web plugin to support this functionality next week.

I'll update you once this task is completed.

**Comment by finnan444** [comment]
@enginseer-dev any updates on this functionality?

**Comment by finnan444** [comment]
By the way [interface InitParams](https://github.com/Pushwoosh/web-push-notifications/blob/401489da1d845c9795383b843f8d3975eab73f13/public/index.d.ts#L211) does not have subscribePopup, so typescript throws exception `Object literal may only specify known properties, and 'subscribePopup' does not exist in type 'InitParams'.ts(2353)
`

**Comment by enginseer-dev** [comment]
@finnan444 Thank you for your patience in resolution of the issue.

In the newest release of [the web SDK](https://github.com/Pushwoosh/web-push-notifications/releases/tag/v3.35.3) we have added manualToggle boolean switch for custom popup.

Here you can find sample and the code example: 
https://pushwoosh-f2364.firebaseapp.com/

You can find the instructions on how to enable and customize the subscription popup for your notifications in our documentation:
https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/web-push-notifications/custom-subscription-popup

**Comment by finnan444** [comment]
@enginseer-dev thank you!

**Comment by finnan444** [comment]
@enginseer-dev should i open new issue for [type problem](https://github.com/Pushwoosh/web-push-notifications/issues/32#issuecomment-2176373026)?

**Comment by enginseer-dev** [comment]
The confusion is caused by the outdated code on our GitHub repository.  
The task is in our backlog and will be fixed.

In the meantime, you can indeed use the subscribePopup as it is fully supported in our latest release, which you can find in the [Releases tab](https://github.com/Pushwoosh/web-push-notifications/releases).

For a practical implementation example of subscribePopup, please refer to this live sample: view-source:https://pushwoosh-f2364.firebaseapp.com/
