### ISSUE TITLE
Lower the level of error to warning

### ISSUE THREAD

**Issue by finnan444** [Pushwoosh/web-push-notifications#33]
When I added pushwoosh script and enabled Firefox and Chrome integration it works fine but I don't want to enable it on Safari. So eventually in my error log system(sentry for example) I see a lot of errors of type `Unhandled Promise Rejection: Error: For work with Safari Push Notification add safariWebsitePushID to initParams!`

<details>
<summary>Screenshot</summary>

![Screenshot 2024-05-31 at 15 56 06](https://github.com/Pushwoosh/web-push-notifications/assets/28092100/bdc94b5b-5c9f-427e-8c87-284e02366dc9)

</details>

I understand that i can ignore this error in logs, but maybe better handle this promise rejection and show warning in console?

**Comment by enginseer-dev** [comment]
Hello @finnan444,
Thank you for pointing this out! I'll pass your request to the corresponding team for further evaluation and let you know the result.

**Comment by enginseer-dev** [comment]
Hey @finnan444,
I want to provide an update. The team will fix this soon, but I can't tell you any ETA yet. Thank you!

**Comment by karudo** [comment]
@finnan444 looks like the problem already fixed
