### ISSUE TITLE
EventDispatcher?

### ISSUE THREAD

**Issue by ReenExe** [Pushwoosh/web-push-notifications#4]
Need event to `pushwooshRegisterDevice`.
I have some algorithm for `setTags`:
1. Get `deviceToken` (as `hwid`)
2. Send `deviceToken` to server - to receive tags for user
3. Set Tags

So need for me do `algorithm` after create `deviceToken` in some callback
Now hardCore write in vendor `pushwoosh-web-notifications.js`, but hope you create some event or callback

**Comment by ReenExe** [comment]
Also can make some Pull Request

**Comment by shaders** [comment]
I'm not sure what you are trying to achieve. Could you please elaborate?

**Comment by ReenExe** [comment]
I think will be good to add some events to lissen changes

**Comment by Andrej-in-ua** [comment]
@shaders, when pushwoosh scripts loading async we can`t be dispatch hwid ready state without change PushwooshBase object. Event on generate hwid can solve this problem.

**Comment by FallDi** [comment]
@Andrej-in-ua @ReenExe We can create public method to getDeviceToken/getDeviceHwid without arguments. This will fix the issue?

**Comment by ReenExe** [comment]
If method expect callback - will be great:

``` javascript
pushwooshInstance.getDeviceToken(function (deviceToken) {
...
})
```

But for me more logical is:

``` javascript
pushwooshInstance.onSetDeviceToken(function (deviceToken) {
...
})
```

**Comment by Andrej-in-ua** [comment]
@FallDi, if this method returned promise it will be exellent. serviceWorkerRegistration.pushManager.getSubscription() - asynchronous method. Our script can execute getDeviceToken/getDeviceHwid before pushwoosh initialized.

**Comment by karudo** [comment]
@ReenExe @Andrej-in-ua we have released new version web sdk (beta)
You can read the documentation here: http://docs.pushwoosh.com/v1.0/docs/web-sdk-20

**Comment by karudo** [comment]
Read & set tags example

``` html
<script type="text/javascript">
Pushwoosh.push(function(api) {
    api.getTags().then(function(result) {
        if (!result.result['My Tag']) {
            return api.setTags({'My Tag': 'value'}).then(function(r) {
                console.log('setTags result', r);
            });
        }
    }).catch(function(e) {
        console.log('error', e);
    });
})
</script>
```

**Comment by Andrej-in-ua** [comment]
@karudo, great job.

@ReenExe, hwid already can take from api.hwid. Example with loading tags from you server:

``` javascript
Pushwoosh.push(function(api) {
    Promise.all([
        api.getTags(),
        youApi.getTagsForUser(api.hwid)
    ]).then((currentRegisteredTag, allTagsForUser) => {
        let tagsDiff = {};
        let hasDiff = false;

        // Added new and modify tags
        for (let tag in allTagsForUser) {
             if (!currentRegisteredTag.result[tag] || currentRegisteredTag.result[tag] != allTagsForUser[tag]) {
                  tagsDiff[tag] = allTagsForUser[tag];
                  hasDiff = true;
             }
        }

        // Remove old tags
        for (let tag in currentRegisteredTag.result) {
             if (!allTagsForUser[tag]) {
                  tagsDiff[tag] = null;
                  hasDiff = true;
             }             
        }

        return hasDiff
            ? api.setTags(tagsDiff)
            : new Promise.resolve(currentRegisteredTag);
    });
});
```

**Comment by ReenExe** [comment]
So wait new SDK
