### ISSUE TITLE
IPhone 6 Sarari `TypeError: undefined is not an object (evaluating 'window.safari.pushNotification')`

### ISSUE THREAD

**Issue by ReenExe** [Pushwoosh/web-push-notifications#5]
from `Tools - Safari for Developers`
![pushwoosh-safari-error](https://cloud.githubusercontent.com/assets/10358615/15848981/b455521a-2c98-11e6-8014-3bfcfe2ac5b2.png)

**Comment by ReenExe** [comment]
Also have same error on IPad

**Comment by shaders** [comment]
We are going to release major update to the SDK this week. This bug will be fixed there. Thanks!
