### ISSUE TITLE
wrong userdata notification on chrome

### ISSUE THREAD

**Issue by superainovacoes** [Pushwoosh/web-push-notifications#6]
Hi, i'm using the remove api /createmessage to send push to my clients.

i'm sending the same content to android/ios/wp/chrome but only on chrome i'm receveing the wrong content and userdata values.

/_NODEJS_/
var Pushwoosh = require('pushwoosh-client');
var clientPW = new Pushwoosh('app id', 'app token');

clientPW.sendMessage('any message', {
    send_date: 'now',
    ignore_user_timezone: true,

```
devices: ['ios id', 'android id', 'wp id', 'chrome id'],

platforms: [1, 3, 5, 9],

data: {     
    title: 'any title'',
    message: 'any message',
    image: 'http://...anyimage.png',
    url: 'http://...anyurl.com'
},

chrome_icon: 'http://...anyimage.png',
firefox_icon: 'http://...anyimage.png',

android_custom_icon: 'http://...anyimage.png',
android_vibration: 1,
android_ibc: '#ffffff'
```

});

https://community.pushwoosh.com/questions/3603/wrong-userdata-notification-on-chrome

**Comment by karudo** [comment]
What do you use site(url) where its happens?

**Comment by superainovacoes** [comment]
mobile devices i receive the correct notification.

chrome - watching the logs at dev tools, the service worker request to pushwoosh api the last message but it returns a message that was send to another client.

**Comment by superainovacoes** [comment]
hi, still not working in the last version

https://community.pushwoosh.com/questions/3603/wrong-userdata-notification-on-chrome

**Comment by superainovacoes** [comment]
fixed more info at https://community.pushwoosh.com/questions/3603/wrong-userdata-notification-on-chrome
