### ISSUE TITLE
Documentation: Web-SDK-20 proposal

### ISSUE THREAD

**Issue by ReenExe** [Pushwoosh/web-push-notifications#9]
[documentation](http://docs.pushwoosh.com/docs/web-sdk-20)
Можете ли Вы добавить дополнительный пример - чтобы подключать одним файлом?

``` javascript
import PushwooshGlobal from 'web-push-notifications/classes/Global';
let pushwoosh = new PushwooshGlobal();
pushwoosh.push(['init', {
    logLevel: 'info', // or debug
    applicationCode: 'DEAD0-BEAF0',
    safariWebsitePushID: 'web.com.example.domain',
    defaultNotificationTitle: 'Pushwoosh',
    defaultNotificationImage: 'https://cp.pushwoosh.com/img/logo-medium.png'
}]);
```

В плане поддерживать такой вариант подключения - чтоб добавить в общую сборку

**Comment by karudo** [comment]
Здравствуйте!
импортить можно проще:

``` javascript
import {Pushwoosh} from 'web-push-notifications';
let pushwoosh = new Pushwoosh();
```

В документацию обязательно добавим, спасибо!

**Comment by ReenExe** [comment]
Да, теперь увидел https://github.com/Pushwoosh/web-push-notifications/blob/master/src/index.js
